# Exported from Render on 2024-08-08T07:51:23Z
databases:
- name: db-savings-sage
  databaseName: savingssage
  user: savingssage_user
  plan: free
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: backend-savings-sage:latest
  runtime: image
  image:
    url: docker.io/kveszti/backend-savings-sage:latest
  plan: free
  envVars:
  - key: DATABASE_PASSWORD
    fromDatabase:
      name: db-savings-sage
      property: password
  - key: DATABASE_USER
    value: savingssage_user
  - key: DATABASE_NAME
    value: savingssage
  - key: DATABASE_HOST
    value: dpg-cqpmdpij1k6c73dt3st0-a.frankfurt-postgres.render.com
  - key: DATABASE_URL
    fromDatabase:
      name: db-savings-sage
      property: connectionString
      value: Host=dpg-cqpmdpij1k6c73dt3st0-a.frankfurt-postgres.render.com;Database=savingssage;Username=savingssage_user;Password=2j2bTjTXlhrhNgKynNQ0ndNMcPLLM2Xs
  region: frankfurt
- type: web
  name: frontend-savings-sage:latest
  runtime: image
  image:
    url: docker.io/kveszti/frontend-savings-sage:latest
  plan: free
  region: frankfurt
version: "1"
