# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
  build-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore      
      working-directory: savings-sage/
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: savings-sage/
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: savings-sage/

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install
        working-directory: savings-sage/Frontend  

      - name: Run npm CI
        run: npm ci
        working-directory: savings-sage/Frontend 

      #- name: Run linter
       # run: npm run lint
        #working-directory: savings-sage/Frontend  

      - name: Build frontend
        run: npm run build
        working-directory: savings-sage/Frontend 
