# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore      
      working-directory: savings-sage/
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: savings-sage/
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: savings-sage/

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install
        working-directory: savings-sage/Frontend  

      - name: Run npm CI
        run: npm ci
        working-directory: savings-sage/Frontend 

      #- name: Run linter
       # run: npm run lint
        #working-directory: savings-sage/Frontend  

      - name: Build frontend
        run: npm run build
        working-directory: savings-sage/Frontend 
        
  push_to_DockerHub:
      name: Push Images to DockerHub
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      # build Docker image and push to docker hub
      # only if the app build and test successfully
      needs: [build-frontend]

      steps:
        - name: checkout repo
          uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: savings-sage/
            file: savings-sage/docker-compose.yml
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/express-demo:latest

        - name: Run the image in a container
          uses: addnab/docker-run-action@v3
          with:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/express-demo:latest
            run: |
              echo "running the docker image"
              echo "Testing the nodejs  app endpoints"
              echo ${{ steps.docker_build.outputs.digest }}
